language: swift

before_install:
   - rvm use system
   - sudo gem install cocoapods -v '1.10.1'

osx_image: xcode12.5
xcode_project: MuviCat.xcodeproj
xcode_scheme: MuviCat
xcode_destination: platform=iOS Simulator,OS=14.5,name=iPhone 11 Pro

script:
    xctool -workspace MuviCat.xcworkspace -scheme MuviCat build -sdk iphonesimulator
